#!/bin/bash

while true
do
	node ./coinigy
	RESULT=$?
	echo "Exit with result $RESULT"
	if [ "$RESULT" -ne "10" ]
	then
		echo "Abnormal restart"
	else
		echo "Restarting because of code change"
	fi
done
