#!/bin/bash

set -e

date

# TODO include 1
HOSTS=`echo fomobot{2,3}`

echo "Deploying `git rev-parse master`" to $HOSTS

# Pre-deploy
git archive master > /tmp/fomobot.tar

function deploy {
	HOST=$1;

	scp /tmp/fomobot.tar $HOST:
	ssh $HOST 'mkdir -p fomobot; tar xvf fomobot.tar -C fomobot; cd fomobot; yarn; forever restart 0'
}

first=1

for HOST in $HOSTS
do
	if [ $first -ne 1 ]
	then
		echo "Taking a nap between deploys..."
		sleep 10
	fi
	first=0

	echo "Deploying to $HOST..."
	deploy $HOST
done

date

