#!/usr/bin/env node

const readline = require('./node/readline');
const util = require('util');

const log = (...args) => {
	const stringify = (s) => {
		if (typeof s === 'string') {
			return s;
		} else {
			return util.inspect(s);
		}
	};

	if (rl) {
		rl.log(args.map(stringify).join(' '));
	} else {
		console.log(...args);
	}
};

let rl;

function prompt() {
	rl = readline.createInterface({
		input: process.stdin,
		output: process.stdin
	});

	rl.question('> ', response => {
		rl.close();
		rl = null;
		log('response:', response);
		// log('test', 123, new Date(), { x: 123, y: [1 , 2, 'x'] });
		prompt();
	});
}

prompt();

setInterval(() => {
	log('test', 123, new Date(), { x: 123, y: [1 , 2, 'x'] });
}, 800);
